version: 0.1
phases:
  pre_build:
    commands:
      - echo Prebuild 
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed 
artifacts:
  files:
    - '**/*'
