phases:
  pre_build:
    commands:
      - echo Prebuild 
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed 
artifacts:
  files:
    - '**/*'
